package repl

import (
	"bufio"
	"fmt"
	"io"

	"github.com/ulricksennick/monkey/lexer"
	"github.com/ulricksennick/monkey/token"
)

const PROMPT = ">> "

func Start(in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)

	for {
		fmt.Printf(PROMPT)
		// Read from input source until encountering a newline
		didScan := scanner.Scan()
		// Return if scan error occurs or scanner reaches end of reader
		if !didScan {
			return
		}

		// Create a lexer with the scanned line of text
		line := scanner.Text()
		l := lexer.New(line)

		// Print tokens generated by the lexer from the input
		for tok := l.NextToken(); tok.Type != token.EOF; tok = l.NextToken() {
			fmt.Printf("%+v\n", tok)
		}
	}
}
